name = "ekho"
description = "Shiny new project"
version = "0.0.0"

authors = ["rami3l"]
maintainers = ["rami3l <rami3l@outlook.com>"]
maintainers-logins = ["rami3l"]

executables = ["ekho"]
[[depends-on]]  # Added by alr
gnatprove = "^11.2.3"  # Added by alr
